package com.aiorderdeliveryagent.backend.observability;

public enum AuditEventType {
	AUTH_LOGIN_SUCCESS,
	AUTH_LOGIN_FAILURE,
	AUTH_REFRESH_SUCCESS,
	AUTH_REFRESH_FAILURE,
	AUTH_REFRESH_REUSE_DETECTED,
	AUTH_LOGOUT,
	AUTH_RATE_LIMITED,
	INTEGRATION_CREATED,
	INTEGRATION_UPDATED,
	INTEGRATION_DELETED,
	AI_TOOL_EXECUTION,
	AI_RESPONSE_GROUNDING
}
