spring.application.name=backend
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=false
spring.flyway.clean-disabled=true

auth.access-token-signing-key=${AUTH_ACCESS_TOKEN_SIGNING_KEY}
auth.access-token-ttl=PT15M
auth.refresh-token-ttl=P30D
